// src/components/ProgressionChart.tsx
import * as React from "react";
import { CartesianGrid, Line, LineChart, XAxis } from "recharts";

import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  type ChartConfig,
  ChartContainer,
  ChartTooltip,
  ChartTooltipContent,
} from "@/components/ui/chart";
import type {
  ConstructorName,
  RacerName,
  SeasonName,
  TrackName,
} from "@/types";
import {
  seasonRacers,
  tracks,
  standings,
  constructors,
  constructorsStandings,
} from "@/data";

export const description = "An interactive line chart";

const chartData = (
  season: SeasonName,
  track: TrackName,
  activeChart: string
) => {
  const dataSet =
    activeChart === "drivers"
      ? Object.entries(standings[season]).map((entry) => [
          entry[0],
          Object.entries(entry[1]).reduce((acc, [key, value]) => {
            acc[key as RacerName] = value.points;
            return acc;
          }, {} as Record<RacerName, number>),
        ])
      : Object.entries(constructorsStandings[season]).map((entry) => [
          entry[0],
          Object.entries(entry[1]).reduce((acc, [key, value]) => {
            acc[key as ConstructorName] = value.normalisedPoints;
            return acc;
          }, {} as Record<ConstructorName, number>),
        ]);

  const sliceIndex =
    (dataSet.findIndex((item) => item[0] === track) ?? dataSet.length - 1) + 1;

  return dataSet.slice(0, sliceIndex).map((race) => ({
    race: tracks[race[0] as TrackName].name,
    ...(typeof race[1] === "object" ? race[1] : {}),
  }));
};

const chartConfig = {
  drivers: {
    label: "Drivers",
    color: "hsl(var(--chart-1))",
  },
  constructorsStandings: {
    label: "Constructors",
    color: "hsl(var(--chart-2))",
  },
} satisfies ChartConfig;

export const ProgressionChart = ({
  season,
  track,
}: {
  season: SeasonName;
  track: TrackName;
}) => {
  const [activeChart, setActiveChart] =
    React.useState<keyof typeof chartConfig>("drivers");

  const seasonDrivers = Object.keys(seasonRacers[season]) as RacerName[];
  const seasonConstructors = Array.from(
    new Set(Object.values(seasonRacers[season]).map((racer) => racer.car))
  );

  const seasonEntities =
    activeChart === "drivers" ? seasonDrivers : seasonConstructors;

  const chartButtons = ["s4", "s5"].includes(season)
    ? ["drivers", "constructorsStandings"]
    : ["drivers"];

  return (
    <Card className="col-span-2">
      <CardHeader className="flex flex-col items-stretch space-y-0 border-b p-0 sm:flex-row">
        <div className="flex flex-1 flex-col justify-center gap-1 px-6 py-5 sm:py-6">
          <CardTitle>Progression</CardTitle>
          <CardDescription>
            Showing progression as of {tracks[track].name}
          </CardDescription>
        </div>
        <div className="flex">
          {chartButtons.map((key) => {
            const chart = key as keyof typeof chartConfig;
            return (
              <button
                key={chart}
                data-active={activeChart === chart}
                className={`flex flex-1 flex-col justify-center gap-1 border-t px-6 py-4 text-left even:border-l last:rounded-tr-lg data-[active=true]:bg-muted/50 sm:border-l sm:border-t-0 sm:px-8 sm:py-6 transition-colors ${
                  activeChart === chart
                    ? "bg-zinc-100 dark:bg-zinc-800"
                    : "hover:bg-zinc-50 hover:dark:bg-zinc-800"
                }`}
                onClick={() => setActiveChart(chart)}
              >
                <span className="text-lg text-muted-foreground">
                  {chartConfig[chart].label}
                </span>
              </button>
            );
          })}
        </div>
      </CardHeader>
      <CardContent className="px-2 sm:p-6">
        <ChartContainer
          config={chartConfig}
          className="aspect-auto h-[500px] w-full"
        >
          <LineChart
            accessibilityLayer
            data={chartData(season, track, activeChart)}
            margin={{
              left: 12,
              right: 12,
            }}
          >
            <CartesianGrid vertical={false} />
            <XAxis
              dataKey="race"
              tickLine={false}
              axisLine={false}
              tickMargin={8}
              minTickGap={32}
            />
            <ChartTooltip
              content={<ChartTooltipContent className="w-[150px]" />}
            />
            {seasonEntities.map((item, index) => {
              const color =
                activeChart === "constructorsStandings"
                  ? constructors[item as ConstructorName].teamColor
                  : `var(--chart-${(index % 5) + 1})`;

              return (
                <Line
                  key={item}
                  dataKey={item}
                  type="monotone"
                  stroke={color}
                  strokeWidth={2}
                  dot={{
                    fill: color,
                  }}
                  activeDot={{
                    r: 6,
                  }}
                />
              );
            })}
          </LineChart>
        </ChartContainer>
      </CardContent>
    </Card>
  );
};

// src/components/ProgressionChart.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { constructorsStandings, tracks } from "@/data";
  import { type SeasonName, type TrackName } from "@/types";
  import Chart, { type ChartConfiguration } from "chart.js/auto";
  import { constructors, drivers, seasonRacers, standings } from "@/data";
  import type { ConstructorName, RacerName } from "@/types";
  import * as Card from "@/components/ui/card";
  import { Button } from "@/components/ui/button";
  import { chartConfig, commonConfig, type ChartType } from "./chart-utils";

  type Props = {
    season: SeasonName;
    track: TrackName;
  };

  const { season, track }: Props = $props();

  let standingsCtx: HTMLCanvasElement;
  let chartInstance: Chart;
  let activeChartType: ChartType = $state("drivers");
  let usePoints = $state(true);

  const seasonStandingKeys = Object.keys(standings[season] ?? {});
  const seasonStandingValues = Object.values(standings[season] ?? {});

  const chartButtons: ChartType[] = ["s4", "s5"].includes(season)
    ? ["drivers", "constructors"]
    : ["drivers"];

  const config: ChartConfiguration<"line", number[], string> = {
    ...commonConfig,
    data: {
      datasets: [],
      labels: seasonStandingKeys
        .slice(0, seasonStandingKeys.indexOf(track) + 1)
        .map((track) => tracks[track as TrackName].name),
    },
  };

  function updateChartData(type: "drivers" | "constructors", points: boolean) {
    activeChartType = type;
    usePoints = points;

    if (chartInstance) {
      const seasonStandingKeys = Object.keys(standings[season] ?? {});
      const seasonStandingValues = Object.values(standings[season] ?? {});

      const driverData = Object.keys(seasonRacers[season])
        .map((driver) => ({
          driver,
          standings: seasonStandingValues
            .slice(0, seasonStandingKeys.indexOf(track) + 1)
            .map((standing) => standing[driver as RacerName]?.points),
          rankings: seasonStandingValues
            .slice(0, seasonStandingKeys.indexOf(track) + 1)
            .map((standing) => {
              const rank = Object.keys(standing).indexOf(driver) + 1;
              return rank === 0 ? -1 : rank;
            }),
        }))
        .sort((a, b) =>
          drivers[a.driver as RacerName].name.localeCompare(
            drivers[b.driver as RacerName].name,
          ),
        );

      const constructorData =
        Object.keys(constructorsStandings[season]).length > 0
          ? Array.from(
              new Set(
                Object.values(seasonRacers[season]).flatMap((racer) => [
                  racer.car,
                  ...Object.values(racer.otherTeams ?? {}).map(
                    (otherTeam) => otherTeam.car,
                  ),
                ]),
              ),
            )
              .map((constructor) => ({
                constructor,
                standings: Object.values(constructorsStandings[season])
                  .slice(0, seasonStandingKeys.indexOf(track) + 1)
                  .map(
                    (standing) => standing[constructor]?.normalisedPoints ?? 0,
                  ),
                rankings: Object.values(constructorsStandings[season])
                  .slice(0, seasonStandingKeys.indexOf(track) + 1)
                  .map((standing) => {
                    const rank = Object.keys(standing).indexOf(constructor) + 1;
                    return rank === 0 ? -1 : rank;
                  }),
              }))
              .sort((a, b) =>
                constructors[
                  a.constructor as ConstructorName
                ].name.localeCompare(
                  constructors[b.constructor as ConstructorName].name,
                ),
              )
          : [];

      const data = type === "drivers" ? driverData : constructorData;
      chartInstance.data.datasets = data.map((item) => ({
        label:
          type === "drivers" && "driver" in item
            ? drivers[item.driver as RacerName].name
            : constructors[item.constructor as ConstructorName].name,
        data: points ? item.standings : item.rankings,
        borderWidth: 2,
        backgroundColor:
          type === "drivers"
            ? undefined
            : constructors[item.constructor as ConstructorName].teamColor,
        borderColor:
          type === "drivers"
            ? undefined
            : constructors[item.constructor as ConstructorName].teamColor,
      }));

      if (chartInstance.options.scales) {
        chartInstance.options.scales.y = {
          ...chartInstance.options.scales.y,
          min: points ? 0 : 1,
          reverse: !points,
        };
      }

      if (chartInstance.options.plugins) {
        chartInstance.options.plugins.tooltip = {
          ...chartInstance.options.plugins.tooltip,
          itemSort: (a: any, b: any) => {
            return points ? b.raw - a.raw : a.raw - b.raw;
          },
        };
      }

      chartInstance.update();
    }
  }

  function toggleAllDatasets(show: boolean) {
    if (chartInstance) {
      // Update dataset visibility
      chartInstance.data.datasets.forEach((dataset) => {
        dataset.hidden = !show;
      });

      chartInstance.legend?.legendItems?.forEach((_, index) => {
        if (chartInstance.legend) {
          chartInstance.legend.options.display = true;
        }
        chartInstance.setDatasetVisibility(index, show);
      });

      chartInstance.update();
    }
  }

  onMount(() => {
    if (standingsCtx) {
      chartInstance = new Chart(standingsCtx, config);
      updateChartData("drivers", true);
    }
  });
</script>

<Card.Root class="col-span-2">
  <Card.Header
    class="flex flex-col items-stretch space-y-0 border-b p-0 md:flex-row"
  >
    <div class="flex flex-1 flex-col justify-center gap-1 px-6 py-5 sm:py-6">
      <Card.Title>Progression</Card.Title>
      <Card.Description>
        Showing progression as of {tracks[track].name}
      </Card.Description>
    </div>
    <div class="flex flex-col z-10 mt-4 sm:mt-0 p-2 gap-2 justify-center">
      <Button
        variant="outline"
        onclick={() => updateChartData(activeChartType, true)}
        >Sort by Points</Button
      >
      <Button
        variant="outline"
        onclick={() => updateChartData(activeChartType, false)}
        >Sort by Rank</Button
      >
    </div>
    <div class="flex">
      {#each chartButtons as chart}
        <button
          onclick={() => updateChartData(chart, usePoints)}
          data-active={`${activeChartType === chart}`}
          class="flex flex-1 flex-col justify-center gap-1 border-t px-6 py-4 text-left even:border-l sm:last:rounded-tr-lg sm:border-l md:border-t-0 sm:px-8 sm:py-6 transition-colors data-[active=true]:bg-zinc-100 dark:data-[active=true]:bg-zinc-800 hover:bg-zinc-200 dark:hover:bg-zinc-700"
        >
          <span class="text-lg text-muted-foreground">
            {chartConfig[chart].label}
          </span>
        </button>
      {/each}
    </div>
  </Card.Header>
  <Card.Content
    class="relative px-2 sm:p-6 sm:pb-0 flex items-start justify-center h-[600px]"
  >
    <canvas
      bind:this={standingsCtx}
      id="standings-chart"
      class="absolute inset-x-0 inset-y-6 sm:inset-6 w-full transition-opacity duration-500 ease-in-out"
    ></canvas>
  </Card.Content>
  <div class="flex justify-center gap-3 p-3">
    <Button onclick={() => toggleAllDatasets(true)} variant="outline"
      >Show All</Button
    >
    <Button onclick={() => toggleAllDatasets(false)} variant="outline"
      >Show None</Button
    >
  </div>
</Card.Root>
